add documentation for cytof assayapp
bihealth/sodar-server pull request #1711
Opened 2023-06-15 10:53 UTC by sellth

2023-06-16 10:27 UTC, mikkonie requested changes

2023-06-16 10:27 UTC, mikkonie commented on docs_manual/source/dev_apps.rst
> +cytof
Let's place these in alphabetical order for clarity.

2023-06-16 10:27 UTC, mikkonie commented on docs_manual/source/metadata_advanced.rst
> +    * Each row links to the **Assay Name** of the **mass cytometry** process node of that row.
Line length over 80 here, please shorten. Other than these two comments, looks good and can merge.

2023-06-20 08:52 UTC, sellth commented
updated to address comments

2023-07-20 07:38 UTC, mikkonie approved these changes

2023-07-20 07:40 UTC, merged