Add "create" tag for sheet versions
bihealth/sodar-server pull request #1728
Opened 2023-07-13 14:01 UTC by gromdimon

## Issue #1296 
### TODO:
- [ ] Implement
- [ ] Test
- [ ] Cleanup

2023-07-17 11:39 UTC, gromdimon commented
## Another Issue: #1723 
### TODO:
- [ ] Implement test


btw: I found an interesting approach to avoid imports of IrodsRequest and ISATab - just mocking them. I hope it works fine, if not - let me know and I will reimplement them.

2023-07-20 12:52 UTC, mikkonie requested changes
Looks good and works just as expected, good work. I have some requests for changes, mainly related to style issues.

These should preferably have been two separate PRs as they are not related in any other way than belonging in the same app, but it's not a big deal since it's not a huge PR.

2023-07-20 12:52 UTC, mikkonie commented on samplesheets/tests/test_templatetags.py
> +        self.irods_backend = get_backend_api("omics_irods")
Double quotes spotted! :)

2023-07-20 12:52 UTC, mikkonie commented on samplesheets/tests/test_templatetags.py
> +            item = {"type": material_type}
More double quotes here and below in the same file.

2023-07-20 12:52 UTC, mikkonie commented on samplesheets/tests/test_templatetags.py
> +    def test_get_isatab_tag_html_with_tags_in_TAG_COLORS(self):
Stlye note, let's not have capitalized letters in method names.

2023-07-20 12:52 UTC, mikkonie commented on samplesheets/tests/test_templatetags.py
> +        expected_trimmed_path = "/project/subfolder1/subfolder2"
For consistency and clarity, we should call variables like this in tests just `expected`, unless several different variables are needed within one test case.

2023-07-20 12:52 UTC, mikkonie commented on samplesheets/tests/test_views.py
>      """Tests for SheetTemplateCreateFormView"""
The class name was updated but the old name remains in the class docstring :)

2023-08-10 14:31 UTC, mikkonie requested changes
A couple of minor notes, can merge after these have been handled.

2023-08-10 14:31 UTC, mikkonie commented on samplesheets/tests/test_templatetags.py
> +        clean_assay_path_0 = self.irods_backend.get_sub_path(self.assay).split(
It seems you are needlessly splitting the same path twice here.

Also, minor notes on conventions: We don't traditionally name variables in the format of `x_0`. The underscore is not needed. Also, since these are only internal variables used inside this one test case, feel free to shorten them a bit :)

2023-08-10 14:31 UTC, mikkonie commented on samplesheets/tests/test_templatetags.py
> +        expected_path = self.irods_backend.get_path(self.project)
We can just name these variables `expected`, unless there are multiple expected values within a single test cases we need to differentiate between.

2023-08-14 14:08 UTC, mikkonie requested changes
Reviewed, had one comment.

2023-08-14 14:08 UTC, mikkonie commented on samplesheets/tests/test_templatetags.py
> +        path0, path1 = self.irods_backend.get_sub_path(self.assay).split('/')
I'm not sure if I understand what happens here. You split the same path into two parts and then assert both of them are found in the return data. Why not just assert the inclusion of the full path?

2023-08-14 18:13 UTC, gromdimon commented on samplesheets/tests/test_templatetags.py
> +        path0, path1 = self.irods_backend.get_sub_path(self.assay).split('/')
The reason for that is response. It is html, which is formed with tags:
`<ul><li>sample_data<ul><li>study_dff42df4-362a-460c-86cf-749897eb6190<ul><li>assay_f9fb2c7d-9541-4a44-a8a3-0bbaebfdb7ce</li></ul></li></ul></li></ul>`
So I've splited path and asserted it separately, as it was the simplest solution :)

2023-08-15 08:07 UTC, mikkonie approved these changes
Looks good, will merge.

2023-08-15 08:09 UTC, merged