Crash in `ZoneStatusRetrieveAjaxView` views from `getlist()`
bihealth/sodar-server pull request #1754
Opened 2023-08-18 09:42 UTC by gromdimon

## Issue: #1752 
### Tasks:
- [x] Fix the bug
- [x] Test it

2023-08-18 10:40 UTC, mikkonie requested changes
Reviewed, found one bug and a style note.

2023-08-18 10:40 UTC, mikkonie commented on landingzones/static/landingzones/js/landingzones.js
> +    if (zoneUuids.length >= 0) {
I'm still seeing requests to the Ajax view even if there are no zones for which to check the status. The condition here should probably be `zoneUuids.length > 0`.

2023-08-18 10:40 UTC, mikkonie commented on landingzones/tests/test_views_ajax.py
> +    def test_post_no_landingzone(self):
Minor style point, `test_post_no_zone()` would probably be more consistent with the naming of other tests. Otherwise this looks good!

2023-08-18 11:11 UTC, gromdimon commented on landingzones/static/landingzones/js/landingzones.js
> +    if (zoneUuids.length >= 0) {
Forgot to return to the `>` after testing :)

2023-08-18 12:44 UTC, mikkonie requested changes
This works now, good job! However, I would like one last bit of refactoring.

2023-08-18 12:44 UTC, mikkonie commented on landingzones/static/landingzones/js/landingzones.js
> +            zoneUuids += zoneUuid + ',';
This latest update to the pr works now, and that's great. However, we should do this in a more standardized way.

The original way of sending this as a list is fine. The problems were that:
1. We were performing the request even when there was nothing to queryt for, and
2. The Ajax view didn't correctly handle not receiving a list.

Converting back and forth between strings adds extra complexity which we don't actually require.

2023-08-18 12:44 UTC, mikkonie commented on landingzones/views_ajax.py
> +        zone_uuids = zone_uuids_string.split(',')[:-1]
As commented in the javascript file, we should still provide and grab a standard list like in the original implementation. Here in the view we just need to check if the value we're looking at is an instance of `QueryDict` before we call `getlist()`.

2023-08-21 07:56 UTC, mikkonie approved these changes
This still works as expected, which is great. The check in the ajax view I specifically asked for is missing, however it doesn't seem that is required with the current way we make requests to the Ajax view. Will merge.

2023-08-21 07:57 UTC, merged