fix: Inline links for material names
bihealth/sodar-server pull request #1983
Opened 2024-08-15 11:26 UTC by sellth

closes #1982

2024-08-30 15:32 UTC, sellth commented
Now also closes #1984. What happens if we try to create links in an ontology or list column? Should we check for that?

2024-09-02 13:43 UTC, mikkonie requested changes
One small note, otherwise this looks good to merge.

2024-09-02 13:43 UTC, mikkonie commented on samplesheets/assayapps/generic/plugins.py
> +        else:
Here we can leave out the `else:` and simply `return None`, as reaching any of the previous clauses returns from the function anyway.

2024-09-02 13:45 UTC, mikkonie commented
> Now also closes #1984. What happens if we try to create links in an ontology or list column? Should we check for that?

I would say these cases should be checked, as long as there's a somewhat-realistic chance someone woult attempt to create links to such columns. I'm not sure if it needs to go in this PR though or if it should be considered an additional feature. You make the call :)

2024-09-02 15:52 UTC, sellth commented
The project might end up in a state which the user cannot recover from without admin help, but it will probably be an edge case. I would prioritise getting these fixes out.

2024-09-05 07:57 UTC, mikkonie approved these changes

2024-09-05 07:57 UTC, merged